### ISSUE TITLE
训练中断

### ISSUE THREAD

**Issue by MR-HOLO** [uncbiag/iSegFormer#4]
你好你好，我这还有个问题

训练如果中断了，我想在原有的基础上继续训练

我看到你有两个参数
--resume-exp 和 --resume-prefix
这两个该如何使用呢，比如我想跑100个epoch ,在80断了，保存了last.pth ,这两个参数如何设置

**Comment by qinliuliuqin** [comment]
你好，我推荐你直接使用 "--weights" 加载已经保存的模型。“--resume-exp” 和 “--resume-prefix” 这两个参数我也没用过，继承自RITM。
