### ISSUE TITLE
Model weights finetuned by COCO_Lvis dataset

### ISSUE THREAD

**Issue by 22TonyFStark** [uncbiag/iSegFormer#5]
It seems that in the readme the model weight loaded for evaluation is imagenet21k_pretrain_cocolvis_finetune_swin_base_epoch_54.pth, however, the weights provided in the [https://drive.google.com/drive/folders/1KG6QVwlydyEzmcKNHgvCZjKhsaycIFiV](url) is fine-tuned by OAI-ZIB, could you provide the weight fine-tuned by COCO_Lvis?
Besides, I test the model imagenet21k_pretrain_oaizib_finetune_swin_base_epoch_54 using ssTEM, and all samples fail (IOU is less than 0.1 with 20 clicks), but it works well for OAI-ZIB, is this phenomenon normal?

**Comment by qinliuliuqin** [comment]
@22TonyFStark Hi, we only provided the best models on OAI-ZIB. Tab. 4 of our paper shows that the models pretrained on IN21K and finetuned on OAI-ZIB achieve the best performance. I should have provided all models a year ago, but at this point, I have lost track of some of my previous experiments-figuring them out may take some time. 
For your second question, yes, that's normal. The OAI-ZIB finetuned models work only well on OAI-ZIB and generalize very badly on other datasets. If you want to try SOTA iSeg models, please checkout our recent work SimpleClick.
