### ISSUE TITLE
代码入口

### ISSUE THREAD

**Issue by shengqianzhu** [uncbiag/iSegFormer#6]
您好，我一直不知道您这个代码入口在哪，我想用您的网络在我自己的医学数据集上跑一下，但是不知道该从哪入手，所以想请教一下。方便的话可以加个微信吗

**Comment by qinliuliuqin** [comment]
@ROSENty Hi, thanks for your interest. If you want to reproduce our [MICCAI 2022 paper](https://arxiv.org/abs/2112.11325), please refer to [v1.0](https://github.com/uncbiag/iSegFormer/tree/v1.0). If you want to reproduce our [latest arXiv paper](https://arxiv.org/abs/2303.06493), please refer to [v2.0](https://github.com/uncbiag/iSegFormer/tree/v2.0). However, v2.0 is still under active development. I will let you know once we finalize our paper. Thanks for your patience! Feel free to add my Wechat: qinliu-liuqin.

**Comment by qinliuliuqin** [comment]
@ROSENty The code in v2.0 is ready now. Feel free to reach out if you have any issues.
