### ISSUE TITLE
NoC

### ISSUE THREAD

**Issue by MR-HOLO** [uncbiag/iSegFormer#7]
你好，还有个问题需要请教一下，NoC的计算方式是按照RITM的来的吗，具体的代码是在哪里啊。感谢

**Comment by qinliuliuqin** [comment]
@MR-HOLO Hi, yes we use the same NoC implementation as in RITM. I believe RITM also adopts the NoC metric from previous works. The implementation is simple. You may refer to [evaluation.py](https://github.com/uncbiag/iSegFormer/blob/v1.0/isegm/inference/evaluation.py) for details. I keep replying in English to make sure the non-Chinese audience can understand the issue.

**Comment by qinliuliuqin** [comment]
Open this issue at any time if you have any more questions.
